volumes:
  cargo-data:

services:
  cargo:
    image: cargo:latest
    ports:
      - "8443:8443"
    volumes:
      - cargo-data:/root/.cargo
      - /var/run/docker.sock:/var/run/docker.sock
  cargo-init:
    image: cargo:latest
    volumes:
      - cargo-data:/root/.cargo
    command:
      - init
    profiles:
      - donotstart