package cmd

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"cargo/internal/sops"
	"cargo/internal/ssl"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Cargo: create workdir, generate SSL cert, age key, and auth token",
	Long: `Initialize Cargo by:
  - Creating the work directory
  - Generating a self-signed SSL certificate and private key
  - Generating an age keypair for SOPS encryption
  - Generating a random auth token for the REST API
  - Writing a sample config.yml`,
	RunE: runInit,
}

func runInit(cmd *cobra.Command, args []string) error {
	workdir, err := resolveWorkdir()
	if err != nil {
		return err
	}

	slog.Info("initializing Cargo", "workdir", workdir)

	// Create workdir
	if err := os.MkdirAll(workdir, 0700); err != nil {
		return fmt.Errorf("creating workdir %q: %w", workdir, err)
	}

	// Create projects subdir
	projectsDir := filepath.Join(workdir, "projects")
	if err := os.MkdirAll(projectsDir, 0755); err != nil {
		return fmt.Errorf("creating projects dir: %w", err)
	}

	// Generate SSL certificate
	fmt.Println("Generating SSL certificate...")
	if err := ssl.SaveCert(workdir); err != nil {
		return fmt.Errorf("generating SSL certificate: %w", err)
	}
	fmt.Printf("  SSL cert saved to: %s\n", filepath.Join(workdir, "cert.pem"))
	fmt.Printf("  SSL key saved to:  %s\n", filepath.Join(workdir, "key.pem"))

	// Generate age keypair for SOPS
	ageKeyPath := filepath.Join(workdir, "age.key")
	fmt.Println("Generating age keypair for SOPS...")
	publicKey, err := sops.GenerateAgeKey(ageKeyPath)
	if err != nil {
		return fmt.Errorf("generating age key: %w", err)
	}
	fmt.Printf("  Age private key saved to: %s\n", ageKeyPath)
	fmt.Printf("  Age public key:           %s\n", publicKey)

	// Generate auth token
	fmt.Println("Generating auth token...")
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil {
		return fmt.Errorf("generating random token: %w", err)
	}
	token := hex.EncodeToString(tokenBytes)

	tokenPath := filepath.Join(workdir, "auth_token")
	if err := os.WriteFile(tokenPath, []byte(token), 0600); err != nil {
		return fmt.Errorf("saving auth token to %q: %w", tokenPath, err)
	}
	fmt.Printf("  Auth token saved to: %s\n", tokenPath)
	fmt.Printf("  Auth token: %s\n", token)

	// Write sample config
	configPath := filepath.Join(workdir, "..", "config.yml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		sampleConfig := buildSampleConfig(workdir, ageKeyPath)
		if err := os.WriteFile(configPath, []byte(sampleConfig), 0644); err != nil {
			slog.Warn("could not write sample config", "path", configPath, "error", err)
		} else {
			fmt.Printf("  Sample config written to: %s\n", configPath)
		}
	} else {
		fmt.Printf("  Config already exists at: %s (skipped)\n", configPath)
	}

	fmt.Println()
	fmt.Println("Cargo initialized successfully!")
	fmt.Printf("  Workdir:    %s\n", workdir)
	fmt.Printf("  Auth token: %s\n", token)
	fmt.Println()
	fmt.Println("To start the server, run:")
	fmt.Printf("  cargo server --config %s\n", configPath)

	return nil
}

func resolveWorkdir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}
	return filepath.Join(home, ".cargo", "workdir"), nil
}

func buildSampleConfig(workdir, ageKeyPath string) string {
	return fmt.Sprintf(`# Cargo configuration file
# Generated by 'cargo init'

# Directory where project repositories and runtime data are stored
workdir: %s

server:
  # Interface to listen on (0.0.0.0 listens on all interfaces)
  host: "0.0.0.0"
  # Port for the HTTPS REST API
  port: 8443

projects:
  - name: my-app
    git:
      url: "https://github.com/example/my-app.git"
      # Branch, tag, or commit hash to checkout
      revision: "main"
      # Optional: path to SSH private key for private repos
      # ssh_key: "~/.ssh/id_rsa"
      # Optional: HTTPS credentials for private repos
      # username: "myuser"
      # password: "mytoken"
    compose:
      # Subfolder within the repository containing the docker-compose.yml
      path: ""
      # Compose file name (default: docker-compose.yml)
      file: "docker-compose.yml"
    # Optional: polling interval (e.g. "5m", "1h", "30s")
    # poll_interval: "5m"
    sops:
      enabled: false
      # Path to the age private key file (generated by 'cargo init')
      age_key: "%s"
      # Path to the encrypted .env file within the repository
      env_file: ".env.enc"
`, workdir, ageKeyPath)
}
